version: "3"

services:
  nginx:
    restart: unless-stopped
    container_name: nginx-cms
    build:
      context: ./compose/docker/nginx
    ports:
      - "3000:80"
    volumes:
      - ./build:/var/www:delegated
      - ./compose/docker/nginx/conf:/etc/nginx/conf.d/
    networks:
      - network-bridge

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  network-bridge:
    driver: bridge
